#===Common===
explicit_timeout=15
auto_screenshot=true

#===Desktop===
#url=https://www.demoblaze.com/index.html
#browser=chrome
#selenium_url=http://localhost:4444/wd/hub
#auto_download=false

#===Android===
driver_type=mobile
capabilities.platformName=Android
capabilities.deviceName=Pixel 6 Pro
capabilities.platformVersion=16.0
capabilities.automationName=UiAutomator2
capabilities.browserName=Chrome
selenium_url=http://127.0.0.1:4723/
